apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipelines-vote-api
    vendor: alticelabs
  name: pipelines-vote-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: pipelines-vote-api
